server {
    listen 80;
    listen [::]:80;

    server_name analytics.sidrahsalaam.com;

    root /home/deploy/apps/sales-analytics-dashboard/frontend;
    index index.html;

    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /analytics {
        proxy_pass http://127.0.0.1:3000/analytics;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
